//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ginger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ginger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;name&quot;: {
        ///      &quot;required&quot;: true,
        ///      &quot;type&quot;: [
        ///        &quot;string&quot;,
        ///        &quot;null&quot;
        ///      ]
        ///    },
        ///    &quot;description&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: [
        ///        &quot;string&quot;,
        ///        &quot;null&quot;
        ///      ]
        ///    },
        ///    &quot;userId&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: [
        ///        &quot;string&quot;,
        ///        &quot;null&quot;
        ///      ]
        ///    },
        ///    &quot;scanDepth&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: &quot;integer&quot;
        ///    },
        ///    &quot;tokenBudget&quot;: {
        ///      &quot;required&quot;: false,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string agnaistic_characterbook_schema {
            get {
                return ResourceManager.GetString("agnaistic_characterbook_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;type&quot;: &quot;object&quot;,
        ///	&quot;properties&quot;: {
        ///		&quot;name&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;description&quot;: {
        ///			&quot;required&quot;: false,
        ///			&quot;type&quot;: [
        ///				&quot;string&quot;,
        ///				&quot;null&quot;
        ///			]
        ///		},
        ///		&quot;culture&quot;: {
        ///			&quot;required&quot;: false,
        ///			&quot;type&quot;: [
        ///				&quot;string&quot;,
        ///				&quot;null&quot;
        ///			]
        ///		},
        ///		&quot;tags&quot;: {
        ///			&quot;required&quot;: false,
        ///			&quot;type&quot;: [
        ///				&quot;array&quot;,
        ///				&quot;null&quot;
        ///			],
        ///			&quot;items&quot;: {
        ///				&quot;type&quot;: [
        ///					&quot;string&quot;,
        ///					&quot;null&quot;
        ///				]
        ///			}
        ///		},
        ///		&quot;scenario&quot;: {
        ///			&quot;required&quot;: false,
        ///			&quot;type&quot;: [
        ///				&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string agnaistic_charactercard_schema {
            get {
                return ResourceManager.GetString("agnaistic_charactercard_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appicon {
            get {
                object obj = ResourceManager.GetObject("appicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__attribute&quot; version=&quot;1.0&quot;&gt;
        ///	&lt;Name&gt;Other/Add attribute&lt;/Name&gt;
        ///	&lt;Title&gt;Attribute&lt;/Title&gt;
        ///	&lt;Description&gt;Add a custom character attribute&lt;/Description&gt;
        ///	&lt;Order&gt;3&lt;/Order&gt;
        ///	&lt;Color&gt;#fefefe&lt;/Color&gt;
        ///	&lt;Multiple&gt;Yes&lt;/Multiple&gt;
        ///	&lt;Flags&gt;__component, __internal&lt;/Flags&gt;
        ///
        ///	&lt;Text id=&quot;name&quot;&gt;
        ///		&lt;Label&gt;Name&lt;/Label&gt;
        ///		&lt;Description&gt;Attribute name. (E.g., Personality, Appearance, Likes, Dislikes, ...)&lt;/Description&gt;
        ///	&lt;/Text&gt;
        ///	&lt;Text id=&quot;text-value&quot; rule=&quot;type:local is text&quot;&gt;
        ///		&lt;Label&gt;Value&lt;/Label&gt;
        ///	&lt;/Tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string attribute_recipe {
            get {
                return ResourceManager.GetString("attribute_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add recipe(s)....
        /// </summary>
        internal static string cap_add_recipe {
            get {
                return ResourceManager.GetString("cap_add_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result.
        /// </summary>
        internal static string cap_bake_no_result {
            get {
                return ResourceManager.GetString("cap_bake_no_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string cap_confirm {
            get {
                return ResourceManager.GetString("cap_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string cap_error {
            get {
                return ResourceManager.GetString("cap_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Ginger.
        /// </summary>
        internal static string cap_exit_app {
            get {
                return ResourceManager.GetString("cap_exit_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export character.
        /// </summary>
        internal static string cap_export_character {
            get {
                return ResourceManager.GetString("cap_export_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t export file.
        /// </summary>
        internal static string cap_export_error {
            get {
                return ResourceManager.GetString("cap_export_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export lorebook.
        /// </summary>
        internal static string cap_export_lorebook {
            get {
                return ResourceManager.GetString("cap_export_lorebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string cap_find {
            get {
                return ResourceManager.GetString("cap_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import character.
        /// </summary>
        internal static string cap_import_character {
            get {
                return ResourceManager.GetString("cap_import_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed.
        /// </summary>
        internal static string cap_import_error {
            get {
                return ResourceManager.GetString("cap_import_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import external recipe.
        /// </summary>
        internal static string cap_import_external_recipe {
            get {
                return ResourceManager.GetString("cap_import_external_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import lorebook.
        /// </summary>
        internal static string cap_import_lorebook {
            get {
                return ResourceManager.GetString("cap_import_lorebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file.
        /// </summary>
        internal static string cap_load_error {
            get {
                return ResourceManager.GetString("cap_load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded with errors.
        /// </summary>
        internal static string cap_load_with_error {
            get {
                return ResourceManager.GetString("cap_load_with_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New character card.
        /// </summary>
        internal static string cap_new_file {
            get {
                return ResourceManager.GetString("cap_new_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open character card.
        /// </summary>
        internal static string cap_open_character_card {
            get {
                return ResourceManager.GetString("cap_open_character_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image.
        /// </summary>
        internal static string cap_open_image {
            get {
                return ResourceManager.GetString("cap_open_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite lorebook.
        /// </summary>
        internal static string cap_overwrite_lorebook {
            get {
                return ResourceManager.GetString("cap_overwrite_lorebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing recipe.
        /// </summary>
        internal static string cap_overwrite_recipe {
            get {
                return ResourceManager.GetString("cap_overwrite_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing snippet.
        /// </summary>
        internal static string cap_overwrite_snippet {
            get {
                return ResourceManager.GetString("cap_overwrite_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste recipe.
        /// </summary>
        internal static string cap_pasted {
            get {
                return ResourceManager.GetString("cap_pasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew recipes.
        /// </summary>
        internal static string cap_reload_recipes {
            get {
                return ResourceManager.GetString("cap_reload_recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string cap_replace {
            get {
                return ResourceManager.GetString("cap_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file.
        /// </summary>
        internal static string cap_save_error {
            get {
                return ResourceManager.GetString("cap_save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save snippet.
        /// </summary>
        internal static string cap_save_snippet {
            get {
                return ResourceManager.GetString("cap_save_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save snippet.
        /// </summary>
        internal static string cap_save_snippet_error {
            get {
                return ResourceManager.GetString("cap_save_snippet_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace pronouns.
        /// </summary>
        internal static string cap_swap_pronouns {
            get {
                return ResourceManager.GetString("cap_swap_pronouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap characteristic {
            get {
                object obj = ResourceManager.GetObject("characteristic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checker {
            get {
                object obj = ResourceManager.GetObject("checker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapsed {
            get {
                object obj = ResourceManager.GetObject("collapsed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap component {
            get {
                object obj = ResourceManager.GetObject("component", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap component_small {
            get {
                object obj = ResourceManager.GetObject("component_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] default_portrait {
            get {
                object obj = ResourceManager.GetObject("default_portrait", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_small {
            get {
                object obj = ResourceManager.GetObject("delete_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_strike {
            get {
                object obj = ResourceManager.GetObject("delete_strike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already open in another process..
        /// </summary>
        internal static string error_already_open {
            get {
                return ResourceManager.GetString("error_already_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baking yielded no result..
        /// </summary>
        internal static string error_bake_no_result {
            get {
                return ResourceManager.GetString("error_bake_no_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no lore to export..
        /// </summary>
        internal static string error_empty_lore {
            get {
                return ResourceManager.GetString("error_empty_lore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets cannot be empty..
        /// </summary>
        internal static string error_empty_snippet {
            get {
                return ResourceManager.GetString("error_empty_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains unsupported or corrupted data. The text was successfully recovered, but Ginger was unable to recover the recipes..
        /// </summary>
        internal static string error_fallback {
            get {
                return ResourceManager.GetString("error_fallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string error_file_not_found {
            get {
                return ResourceManager.GetString("error_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open help documentation..
        /// </summary>
        internal static string error_help {
            get {
                return ResourceManager.GetString("error_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch text editor.
        /// </summary>
        internal static string error_launch_text_editor {
            get {
                return ResourceManager.GetString("error_launch_text_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load dictionary..
        /// </summary>
        internal static string error_load_dictionary {
            get {
                return ResourceManager.GetString("error_load_dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load image..
        /// </summary>
        internal static string error_load_image {
            get {
                return ResourceManager.GetString("error_load_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of characters reached..
        /// </summary>
        internal static string error_max_characters {
            get {
                return ResourceManager.GetString("error_max_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains no character data..
        /// </summary>
        internal static string error_no_data {
            get {
                return ResourceManager.GetString("error_no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains no lorebook data..
        /// </summary>
        internal static string error_no_lorebook {
            get {
                return ResourceManager.GetString("error_no_lorebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized character card format..
        /// </summary>
        internal static string error_open_character_card {
            get {
                return ResourceManager.GetString("error_open_character_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} recipe(s) could not be added..
        /// </summary>
        internal static string error_pasted {
            get {
                return ResourceManager.GetString("error_pasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read data..
        /// </summary>
        internal static string error_read_data {
            get {
                return ResourceManager.GetString("error_read_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read from json file..
        /// </summary>
        internal static string error_read_json {
            get {
                return ResourceManager.GetString("error_read_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save character card.
        /// </summary>
        internal static string error_save_character_card {
            get {
                return ResourceManager.GetString("error_save_character_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save lorebook..
        /// </summary>
        internal static string error_save_lorebook {
            get {
                return ResourceManager.GetString("error_save_lorebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save notes..
        /// </summary>
        internal static string error_save_notes {
            get {
                return ResourceManager.GetString("error_save_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save snippet..
        /// </summary>
        internal static string error_save_snippet {
            get {
                return ResourceManager.GetString("error_save_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized character format..
        /// </summary>
        internal static string error_unrecognized_character_format {
            get {
                return ResourceManager.GetString("error_unrecognized_character_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized lorebook format..
        /// </summary>
        internal static string error_unrecognized_lorebook_format {
            get {
                return ResourceManager.GetString("error_unrecognized_lorebook_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write to json file..
        /// </summary>
        internal static string error_write_json {
            get {
                return ResourceManager.GetString("error_write_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__example&quot;&gt;
        ///	&lt;Name&gt;Example chat&lt;/Name&gt;
        ///	&lt;Color&gt;FloralWhite&lt;/Color&gt;
        ///	&lt;Order&gt;5&lt;/Order&gt;
        ///	&lt;Multiple&gt;True&lt;/Multiple&gt;
        ///	&lt;Flags&gt;example-dialogue, __example, __component, __formatting, __internal&lt;/Flags&gt;
        ///
        ///	&lt;!-- Parameters --&gt;
        ///	&lt;Text id=&quot;example&quot; style=&quot;chat&quot; mandatory=&quot;true&quot;&gt;
        ///		&lt;Label&gt;Dialogue&lt;/Label&gt;
        ///		&lt;Default&gt;
        ///		[user]: &quot;Hi, my name is [user].&quot;
        ///		[char]: &quot;I&apos;m [char]. Nice to meet you [user]!&quot; *[they] reach[es] out to shake [#their] hand.*
        ///		&lt;/Default&gt;
        ///	&lt;/Text&gt;
        ///
        ///	&lt;Example&gt;{example:local [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example_recipe {
            get {
                return ResourceManager.GetString("example_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expanded {
            get {
                object obj = ResourceManager.GetObject("expanded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;type&quot;: &quot;object&quot;,
        ///	&quot;properties&quot;: {
        ///		&quot;character&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;object&quot;,
        ///			&quot;properties&quot;: {
        ///				&quot;Chat&quot;: {
        ///					&quot;required&quot;: false,
        ///					&quot;type&quot;: [
        ///						&quot;array&quot;,
        ///						&quot;null&quot;
        ///					],
        ///					&quot;items&quot;: {
        ///						&quot;type&quot;: [
        ///							&quot;object&quot;,
        ///							&quot;null&quot;
        ///						],
        ///						&quot;properties&quot;: {
        ///							&quot;name&quot;: {
        ///								&quot;required&quot;: false,
        ///								&quot;type&quot;: [
        ///									&quot;string&quot;,
        ///									&quot;null&quot;
        ///								]
        ///							},
        ///							&quot;modelConfigId&quot;: {
        ///								&quot;required&quot;: false,
        ///								&quot;type&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string faraday_charactercard_v3_schema {
            get {
                return ResourceManager.GetString("faraday_charactercard_v3_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;type&quot;: &quot;object&quot;,
        ///	&quot;properties&quot;: {
        ///		&quot;character&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;object&quot;,
        ///			&quot;properties&quot;: {
        ///				&quot;Chat&quot;: {
        ///					&quot;required&quot;: false,
        ///					&quot;type&quot;: [
        ///						&quot;array&quot;,
        ///						&quot;null&quot;
        ///					],
        ///					&quot;items&quot;: {
        ///						&quot;type&quot;: [
        ///							&quot;object&quot;,
        ///							&quot;null&quot;
        ///						],
        ///						&quot;properties&quot;: {
        ///							&quot;name&quot;: {
        ///								&quot;required&quot;: false,
        ///								&quot;type&quot;: [
        ///									&quot;string&quot;,
        ///									&quot;null&quot;
        ///								]
        ///							},
        ///							&quot;modelConfigId&quot;: {
        ///								&quot;required&quot;: false,
        ///								&quot;type&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string faraday_charactercard_v4_schema {
            get {
                return ResourceManager.GetString("faraday_charactercard_v4_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__grammar&quot;&gt;
        ///	&lt;Name&gt;Other/Grammar&lt;/Name&gt;
        ///	&lt;Description&gt;
        ///		Custom grammar definition.
        ///		(Only supported in Backyard AI.)
        ///	&lt;/Description&gt;
        ///	&lt;Color&gt;#bfd0db&lt;/Color&gt;
        ///	&lt;Order&gt;2&lt;/Order&gt;
        ///	&lt;Requires&gt;not (grammar or __actor)&lt;/Requires&gt;
        ///	&lt;Flags&gt;grammar, __grammar, __component, __internal&lt;/Flags&gt;
        ///	
        ///	&lt;Text id=&quot;grammar&quot; style=&quot;code&quot; raw=&quot;yes&quot;&gt;
        ///			&lt;Label&gt;Grammar&lt;/Label&gt;
        ///			&lt;Default&gt;&lt;![CDATA[root ::= text &quot;\n#&quot;
        ///text ::= [[a-zA-Z0-9,.?!&quot; &apos;:;\n]]+]]&gt;&lt;/Default&gt;
        ///		&lt;/Text&gt;
        ///
        ///	&lt;Grammar&gt;{grammar:local}&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string grammar_recipe {
            get {
                return ResourceManager.GetString("grammar_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__greeting&quot;&gt;
        ///	&lt;Name&gt;Greeting&lt;/Name&gt;
        ///	&lt;Order&gt;4&lt;/Order&gt;
        ///	&lt;Color&gt;FloralWhite&lt;/Color&gt;
        ///	&lt;Multiple&gt;True&lt;/Multiple&gt;
        ///	&lt;Requires&gt;not __actor&lt;/Requires&gt;
        ///	&lt;Flags&gt;greeting, __greeting,  __component, __formatting, __internal&lt;/Flags&gt;
        ///	
        ///	&lt;!-- Parameters --&gt;
        ///	&lt;Text id=&quot;greeting&quot; style=&quot;component&quot;&gt;
        ///		&lt;Label&gt;Message&lt;/Label&gt;
        ///	&lt;/Text&gt;
        ///	
        ///	&lt;Greeting&gt;{greeting:local}&lt;/Greeting&gt;
        ///&lt;/Ginger&gt;.
        /// </summary>
        internal static string greeting_recipe {
            get {
                return ResourceManager.GetString("greeting_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__internal&quot;&gt;
        ///	&lt;!-- Root nodes --&gt;
        ///	&lt;Node path=&quot;system&quot; style=&quot;paragraph&quot; mode=&quot;exclude&quot;/&gt;
        ///	&lt;Node path=&quot;persona&quot; style=&quot;paragraph&quot; mode=&quot;exclude&quot;/&gt;
        ///	&lt;Node path=&quot;scenario&quot; style=&quot;paragraph&quot; mode=&quot;exclude&quot;/&gt;
        ///	&lt;Node path=&quot;user&quot; style=&quot;paragraph&quot; mode=&quot;exclude&quot;/&gt;
        ///	&lt;Node path=&quot;example&quot; style=&quot;paragraph&quot; mode=&quot;exclude&quot;/&gt;
        ///	
        ///	&lt;!-- Standard output --&gt;
        ///	&lt;Node path=&quot;system/output&quot; style=&quot;paragraph&quot; order=&quot;500&quot; mode=&quot;exclude&quot;/&gt;
        ///	&lt;Node path=&quot;persona/output&quot; style=&quot;line&quot; order=&quot;500&quot; mode=&quot;exclude&quot;/&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string internal_global_recipe {
            get {
                return ResourceManager.GetString("internal_global_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger&gt;
        ///	&lt;!-- Macros --&gt;
        ///	&lt;Macro id=&quot;characters, bots&quot;&gt;[names.list]&lt;/Macro&gt;
        ///	&lt;Macro id=&quot;everyone&quot;&gt;[!list:[user];[char];[actors]]&lt;/Macro&gt;
        ///	&lt;Wrapper id=&quot;abbr&quot;&gt;[noparse]_[parse][nocap]&lt;/Wrapper&gt;
        ///	&lt;Wrapper id=&quot;raw&quot;&gt;[noparse]_[parse]&lt;/Wrapper&gt;
        ///	&lt;Wrapper id=&quot;property-label&quot;&gt;_:[sp]&lt;/Wrapper&gt;
        ///
        ///	&lt;!-- Chat style --&gt;
        ///	&lt;Rule id=&quot;is-faraday&quot;&gt;__faraday or __backyard&lt;/Rule&gt;
        ///	&lt;Wrapper id=&quot;dialogue, dialog&quot;&gt;[@dialogue-symbol-open]_[@dialogue-symbol-close]&lt;/Wrapper&gt;
        ///	&lt;Wrapper id=&quot;action, narrate, narration&quot;&gt;[@act [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string internal_macros {
            get {
                return ResourceManager.GetString("internal_macros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lore {
            get {
                object obj = ResourceManager.GetObject("lore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lore_down {
            get {
                object obj = ResourceManager.GetObject("lore_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lore_small {
            get {
                object obj = ResourceManager.GetObject("lore_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lore_up {
            get {
                object obj = ResourceManager.GetObject("lore_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__lorebook&quot;&gt;
        ///	&lt;Name&gt;New lorebook&lt;/Name&gt;
        ///	&lt;Title&gt;Lorebook&lt;/Title&gt;
        ///	&lt;Color&gt;#f2e6f2&lt;/Color&gt;
        ///	&lt;Order&gt;0&lt;/Order&gt;
        ///	&lt;Multiple&gt;True&lt;/Multiple&gt;
        ///	&lt;Flags&gt;lorebook, __lorebook, __component, __internal, __lorebook, __nobake, __hidden&lt;/Flags&gt;
        ///	&lt;!-- Parameters --&gt;
        ///	&lt;__Lorebook id=&quot;book&quot; mandatory=&quot;false&quot;/&gt;
        ///
        ///&lt;/Ginger&gt;.
        /// </summary>
        internal static string lorebook_recipe {
            get {
                return ResourceManager.GetString("lorebook_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap model {
            get {
                object obj = ResourceManager.GetObject("model", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will allow &quot;not safe for work&quot; content, which can include mature themes and potentially offensive material. Continue?.
        /// </summary>
        internal static string msg_confirm_nsfw {
            get {
                return ResourceManager.GetString("msg_confirm_nsfw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss changes?.
        /// </summary>
        internal static string msg_dismiss_changes {
            get {
                return ResourceManager.GetString("msg_dismiss_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No portrait image.
        /// </summary>
        internal static string msg_drop_image {
            get {
                return ResourceManager.GetString("msg_drop_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you also like to add {0} complementary recipe?.
        /// </summary>
        internal static string msg_include_recipe {
            get {
                return ResourceManager.GetString("msg_include_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you also like to add {0} complementary recipes?.
        /// </summary>
        internal static string msg_include_recipes {
            get {
                return ResourceManager.GetString("msg_include_recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists.
        ///Do you want to replace it?.
        /// </summary>
        internal static string msg_incremental_file_exists {
            get {
                return ResourceManager.GetString("msg_incremental_file_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card loaded successfully, but with {0} error(s).
        ///Some data may be missing..
        /// </summary>
        internal static string msg_load_with_error {
            get {
                return ResourceManager.GetString("msg_load_with_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found..
        /// </summary>
        internal static string msg_no_match {
            get {
                return ResourceManager.GetString("msg_no_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This image file contains character data.
        ///Would you like to open it as a character card instead?.
        /// </summary>
        internal static string msg_open_image_card {
            get {
                return ResourceManager.GetString("msg_open_image_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lorebook with the same name already exists.
        ///Would you like to overwrite it?.
        /// </summary>
        internal static string msg_overwrite_lorebook {
            get {
                return ResourceManager.GetString("msg_overwrite_lorebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A recipe with the same name already exists.
        ///Would you like to overwrite it?.
        /// </summary>
        internal static string msg_overwrite_recipe {
            get {
                return ResourceManager.GetString("msg_overwrite_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A snippet with the same name already exists.
        ///Would you like to overwrite it?.
        /// </summary>
        internal static string msg_overwrite_snippet {
            get {
                return ResourceManager.GetString("msg_overwrite_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to renew the recipes in the character cards?.
        /// </summary>
        internal static string msg_reload_recipes {
            get {
                return ResourceManager.GetString("msg_reload_recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurrences replaced..
        /// </summary>
        internal static string msg_replace_plural {
            get {
                return ResourceManager.GetString("msg_replace_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurence replaced..
        /// </summary>
        internal static string msg_replace_single {
            get {
                return ResourceManager.GetString("msg_replace_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string msg_save_changes {
            get {
                return ResourceManager.GetString("msg_save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap persona {
            get {
                object obj = ResourceManager.GetObject("persona", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__persona&quot;&gt;
        ///	&lt;Name&gt;Character persona&lt;/Name&gt;
        ///	&lt;Order&gt;1&lt;/Order&gt;
        ///	&lt;Color&gt;HoneyDew&lt;/Color&gt;
        ///	&lt;Multiple&gt;True&lt;/Multiple&gt;
        ///	&lt;Flags&gt;persona, __persona, __component, __formatting, __internal&lt;/Flags&gt;
        ///	
        ///	&lt;!-- Parameters --&gt;
        ///	&lt;Text id=&quot;persona&quot; style=&quot;component&quot;&gt;
        ///		&lt;Label&gt;Description&lt;/Label&gt;
        ///	&lt;/Text&gt;
        ///	
        ///	&lt;Persona&gt;{persona:local}&lt;/Persona&gt;
        ///&lt;/Ginger&gt;.
        /// </summary>
        internal static string persona_recipe {
            get {
                return ResourceManager.GetString("persona_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap personality {
            get {
                object obj = ResourceManager.GetObject("personality", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__personality&quot;&gt;
        ///	&lt;Name&gt;Other/Personality summary&lt;/Name&gt;
        ///	&lt;Title&gt;Personality summary&lt;/Title&gt;
        ///	&lt;Description&gt;
        ///		This is equivalent to the &quot;Personality summary&quot; field in SillyTavern.
        ///		(Used for compatibility)
        ///	&lt;/Description&gt;
        ///	&lt;Order&gt;1&lt;/Order&gt;
        ///	&lt;Multiple&gt;True&lt;/Multiple&gt;
        ///	&lt;Flags&gt;persona, __personality, __component, __internal&lt;/Flags&gt;
        ///	
        ///	&lt;Text id=&quot;personality&quot; style=&quot;component&quot;&gt;
        ///		&lt;Label&gt;Personality&lt;/Label&gt;
        ///	&lt;/Text&gt;
        ///	
        ///	&lt;Node path=&quot;persona/output/personality&quot; style=&quot;space&quot; order=&quot;1000&quot; m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string personality_recipe {
            get {
                return ResourceManager.GetString("personality_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__post-history&quot;&gt;
        ///	&lt;Name&gt;Other/Model instructions (Important)&lt;/Name&gt;
        ///	&lt;Description&gt;
        ///		Equivalent to the &quot;Jailbreak&quot;/&quot;Post history instructions&quot; field in SillyTavern.
        ///		(Used for compatibility.)
        ///	&lt;/Description&gt;
        ///	&lt;Color&gt;#bfd0db&lt;/Color&gt;
        ///	&lt;Order&gt;0&lt;/Order&gt;
        ///	&lt;Multiple&gt;True&lt;/Multiple&gt;
        ///	&lt;Requires&gt;not __actor&lt;/Requires&gt;
        ///	&lt;Flags&gt;system-prompt, model, __post-history, __component, __formatting, __internal&lt;/Flags&gt;
        ///	
        ///	&lt;Text id=&quot;system&quot; style=&quot;component&quot;&gt;
        ///		&lt;Label&gt;Instructions&lt;/Label&gt;
        ///	&lt;/Text&gt;
        ///	        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string post_history_recipe {
            get {
                return ResourceManager.GetString("post_history_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;type&quot;: &quot;object&quot;,
        ///	&quot;properties&quot;: {
        ///		&quot;char_name&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;char_persona&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;world_scenario&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;char_greeting&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;example_dialogue&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;metadata&quot;: {
        ///			&quot;required&quot;: false,
        ///			&quot;type&quot;: [
        ///				&quot;object&quot;,
        ///				&quot;null&quot;
        ///			],
        ///			&quot;properties&quot;: {
        ///				&quot;vers [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pygmalion_charactercard_schema {
            get {
                return ResourceManager.GetString("pygmalion_charactercard_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger version=&quot;1.0&quot;&gt;
        ///	&lt;!-- Preamble --&gt;
        ///	&lt;Name&gt;%%NAME%%&lt;/Name&gt;
        ///	&lt;Title&gt;%%TITLE%%&lt;/Title&gt;
        ///	&lt;Author&gt;%%AUTHOR%%&lt;/Author&gt;
        ///	&lt;Category&gt;%%CATEGORY%%&lt;/Category&gt;
        ///	&lt;Requires&gt;not base&lt;/Requires&gt;
        ///	&lt;Flags&gt;base&lt;/Flags&gt;
        ///	&lt;Description&gt;
        ///		&lt;!-- Recipe information here --&gt;
        ///	&lt;/Description&gt;
        ///	
        ///	&lt;!-- Parameters? --&gt;
        ///	
        ///	&lt;!-- Output --&gt;
        ///
        ///	&lt;System&gt; 
        ///		&lt;!-- Model instructions here --&gt;
        ///	&lt;/System&gt;
        ///	
        ///&lt;/Ginger&gt;.
        /// </summary>
        internal static string recipe_template_base {
            get {
                return ResourceManager.GetString("recipe_template_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger version=&quot;1.0&quot;&gt;
        ///	&lt;!-- Preamble --&gt;
        ///	&lt;Name&gt;%%NAME%%&lt;/Name&gt;
        ///	&lt;Title&gt;%%TITLE%%&lt;/Title&gt;
        ///	&lt;Author&gt;%%AUTHOR%%&lt;/Author&gt;
        ///	&lt;Category&gt;%%CATEGORY%%&lt;/Category&gt;
        ///	&lt;Flags&gt;%%FLAGS%%&lt;/Flags&gt;
        ///	&lt;Description&gt;
        ///		&lt;!-- Recipe information here --&gt;
        ///	&lt;/Description&gt;
        ///	
        ///	&lt;!-- Parameters? --&gt;
        ///	
        ///	&lt;!-- Output --&gt;
        ///%%NODES%%%%ATTRIBUTES%%%%SYSTEM%%%%POSTHISTORY%%%%PERSONA%%%%USER%%%%SCENARIO%%%%GREETING%%%%EXAMPLE%%%%GRAMMAR%%%%LORE%%&lt;/Ginger&gt;.
        /// </summary>
        internal static string recipe_template_card {
            get {
                return ResourceManager.GetString("recipe_template_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger version=&quot;1.0&quot;&gt;
        ///	&lt;!-- Preamble --&gt;
        ///	&lt;Name&gt;%%NAME%%&lt;/Name&gt;
        ///	&lt;Title&gt;%%TITLE%%&lt;/Title&gt;
        ///	&lt;Author&gt;%%AUTHOR%%&lt;/Author&gt;
        ///	&lt;Category&gt;%%CATEGORY%%&lt;/Category&gt;
        ///	&lt;Description&gt;
        ///		&lt;!-- Recipe details here --&gt;
        ///	&lt;/Description&gt;
        ///	
        ///	&lt;!-- Output --&gt;
        ///	&lt;Persona&gt; 
        ///		&lt;!-- Character description here --&gt;
        ///	&lt;/Persona&gt;
        ///&lt;/Ginger&gt;.
        /// </summary>
        internal static string recipe_template_empty {
            get {
                return ResourceManager.GetString("recipe_template_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger version=&quot;1.0&quot;&gt;
        ///	&lt;!-- Preamble --&gt;
        ///	&lt;Name&gt;%%NAME%%&lt;/Name&gt;
        ///	&lt;Title&gt;%%TITLE%%&lt;/Title&gt;
        ///	&lt;Author&gt;%%AUTHOR%%&lt;/Author&gt;
        ///	&lt;Category&gt;%%CATEGORY%%&lt;/Category&gt;
        ///	&lt;Description&gt;
        ///		&lt;!-- Recipe information here --&gt;
        ///	&lt;/Description&gt;
        ///
        ///	&lt;!-- Output --&gt;
        ///	
        ///	&lt;Attribute&gt;
        ///		&lt;Name&gt;Personality&lt;/Name&gt;
        ///		&lt;Value&gt;&lt;!-- Personality traits, separated by commas --&gt;&lt;/Value&gt;
        ///	&lt;/Attribute&gt;
        ///
        ///	&lt;Attribute&gt;
        ///		&lt;Name&gt;Likes&lt;/Name&gt;
        ///		&lt;Value&gt;&lt;!-- Likes, separated by commas --&gt;&lt;/Value&gt;
        ///	&lt;/Attribute&gt;
        ///
        ///	&lt;Attribute&gt;
        ///		&lt;Name&gt;Disl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recipe_template_personality {
            get {
                return ResourceManager.GetString("recipe_template_personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger version=&quot;1.0&quot;&gt;
        ///	&lt;!-- Preamble --&gt;
        ///	&lt;Name&gt;%%NAME%%&lt;/Name&gt;
        ///	&lt;Title&gt;%%TITLE%%&lt;/Title&gt;
        ///	&lt;Author&gt;%%AUTHOR%%&lt;/Author&gt;
        ///	&lt;Category&gt;%%CATEGORY%%&lt;/Category&gt;
        ///	&lt;Description&gt;
        ///		Sample recipe of a character trait
        ///	&lt;/Description&gt;
        ///		
        ///	&lt;!-- Output --&gt;
        ///	
        ///	&lt;Persona&gt;
        ///		Two large horns, like those of a ram, protrude from [char&apos;s] forehead, curling up and around her head.
        ///	&lt;/Persona&gt;
        ///
        ///&lt;/Ginger&gt;.
        /// </summary>
        internal static string recipe_template_sample_1 {
            get {
                return ResourceManager.GetString("recipe_template_sample_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger version=&quot;1.0&quot;&gt;
        ///	&lt;!-- Preamble --&gt;
        ///	&lt;Name&gt;%%NAME%%&lt;/Name&gt;
        ///	&lt;Title&gt;%%TITLE%%&lt;/Title&gt;
        ///	&lt;Author&gt;%%AUTHOR%%&lt;/Author&gt;
        ///	&lt;Category&gt;%%CATEGORY%%&lt;/Category&gt;
        ///	&lt;Description&gt;
        ///		Sample recipe with parameters.
        ///	&lt;/Description&gt;
        ///	
        ///	&lt;!-- Parameters --&gt;
        ///
        ///	&lt;!-- A drop-down list --&gt;
        ///	&lt;Choice id=&quot;my-choice&quot;&gt;
        ///		&lt;Label&gt;A choice&lt;/Label&gt;
        ///		&lt;Option id=&quot;choice-1&quot;&gt;Choice #1&lt;/Option&gt;
        ///		&lt;Option id=&quot;choice-2&quot;&gt;Choice #2&lt;/Option&gt;
        ///		&lt;Option id=&quot;choice-3&quot;&gt;Choice #3&lt;/Option&gt;
        ///	&lt;/Choice&gt;
        ///	
        ///	&lt;!-- A text field --&gt;
        ///	&lt;Tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recipe_template_sample_2 {
            get {
                return ResourceManager.GetString("recipe_template_sample_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger version=&quot;1.0&quot;&gt;
        ///	&lt;!-- Preamble --&gt;
        ///	&lt;Name&gt;%%NAME%%&lt;/Name&gt;
        ///	&lt;Title&gt;%%TITLE%%&lt;/Title&gt;
        ///	&lt;Author&gt;%%AUTHOR%%&lt;/Author&gt;
        ///	&lt;Category&gt;%%CATEGORY%%&lt;/Category&gt;
        ///	&lt;Description&gt;
        ///		Sample recipe with lore book entries.
        ///	&lt;/Description&gt;
        ///	
        ///	&lt;!-- Parameters --&gt;
        ///
        ///	&lt;Choice id=&quot;lore-kind&quot; mandatory=&quot;true&quot;&gt;
        ///		&lt;Label&gt;Lore kind&lt;/Label&gt;
        ///		&lt;Option id=&quot;fruits&quot;&gt;Fruits&lt;/Option&gt;
        ///		&lt;Option id=&quot;vegetables&quot;&gt;Vegetables&lt;/Option&gt;
        ///	&lt;/Choice&gt;
        ///	
        ///	&lt;!-- Output --&gt;
        ///
        ///	&lt;Lore rule=&quot;fruits&quot;&gt;
        ///		&lt;Name&gt;Apple&lt;/Name&gt;
        ///		&lt;Value&gt;An a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recipe_template_sample_3 {
            get {
                return ResourceManager.GetString("recipe_template_sample_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__scenario&quot;&gt;
        ///	&lt;Name&gt;Scenario&lt;/Name&gt;
        ///	&lt;Order&gt;3&lt;/Order&gt;
        ///	&lt;Color&gt;Linen&lt;/Color&gt;
        ///	&lt;Multiple&gt;True&lt;/Multiple&gt;
        ///	&lt;Flags&gt;scenario, __scenario, __component, __formatting, __internal&lt;/Flags&gt;
        ///	
        ///	&lt;!-- Parameters --&gt;
        ///	&lt;Text id=&quot;scenario&quot; style=&quot;component&quot;&gt;
        ///		&lt;Label&gt;Scenario&lt;/Label&gt;
        ///	&lt;/Text&gt;
        ///	
        ///	&lt;Scenario&gt;{scenario:local}&lt;/Scenario&gt;
        ///&lt;/Ginger&gt;.
        /// </summary>
        internal static string scenario_recipe {
            get {
                return ResourceManager.GetString("scenario_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snippet {
            get {
                object obj = ResourceManager.GetObject("snippet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snippet_small {
            get {
                object obj = ResourceManager.GetObject("snippet_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger format=&quot;1&quot;&gt;
        ///	&lt;Name&gt;%%NAME%%&lt;/Name&gt;
        ///	&lt;Author&gt;%%AUTHOR%%&lt;/Author&gt;
        ///
        ///%%SYSTEM%%%%POSTHISTORY%%%%PERSONA%%%%USER%%%%SCENARIO%%%%GREETING%%%%EXAMPLE%%%%GRAMMAR%%&lt;/Ginger&gt;.
        /// </summary>
        internal static string snippet_template {
            get {
                return ResourceManager.GetString("snippet_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap story {
            get {
                object obj = ResourceManager.GetObject("story", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__system&quot;&gt;
        ///	&lt;Name&gt;Model instructions&lt;/Name&gt;
        ///	&lt;Order&gt;0&lt;/Order&gt;
        ///	&lt;Color&gt;#bfd0db&lt;/Color&gt;
        ///	&lt;Multiple&gt;True&lt;/Multiple&gt;
        ///	&lt;Requires&gt;not __actor&lt;/Requires&gt;
        ///	&lt;Flags&gt;system-prompt, model, __system, __component, __formatting, __internal&lt;/Flags&gt;
        ///	
        ///	&lt;!-- Parameters --&gt;
        ///	&lt;Text id=&quot;system&quot; style=&quot;component&quot;&gt;
        ///		&lt;Label&gt;Instructions&lt;/Label&gt;
        ///	&lt;/Text&gt;
        ///	
        ///	&lt;System&gt;{system:local}&lt;/System&gt;
        ///&lt;/Ginger&gt;.
        /// </summary>
        internal static string system_recipe {
            get {
                return ResourceManager.GetString("system_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;name&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: [
        ///        &quot;string&quot;,
        ///        &quot;null&quot;
        ///      ]
        ///    },
        ///    &quot;description&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: [
        ///        &quot;string&quot;,
        ///        &quot;null&quot;
        ///      ]
        ///    },
        ///    &quot;scan_depth&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: &quot;integer&quot;
        ///    },
        ///    &quot;token_budget&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: &quot;integer&quot;
        ///    },
        ///    &quot;recursive_scanning&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: &quot;boolean&quot;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tavern_characterbook_schema {
            get {
                return ResourceManager.GetString("tavern_characterbook_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;type&quot;: &quot;object&quot;,
        ///	&quot;properties&quot;: {
        ///		&quot;name&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;description&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;personality&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;scenario&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;first_mes&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;mes_example&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;string&quot;
        ///		}
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string tavern_charactercard_v1_schema {
            get {
                return ResourceManager.GetString("tavern_charactercard_v1_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;type&quot;: &quot;object&quot;,
        ///	&quot;properties&quot;: {
        ///		&quot;data&quot;: {
        ///			&quot;required&quot;: true,
        ///			&quot;type&quot;: &quot;object&quot;,
        ///			&quot;properties&quot;: {
        ///				&quot;name&quot;: {
        ///					&quot;required&quot;: false,
        ///					&quot;type&quot;: &quot;string&quot;
        ///				},
        ///				&quot;description&quot;: {
        ///					&quot;required&quot;: false,
        ///					&quot;type&quot;: [
        ///						&quot;string&quot;,
        ///						&quot;null&quot;
        ///					]
        ///				},
        ///				&quot;personality&quot;: {
        ///					&quot;required&quot;: false,
        ///					&quot;type&quot;: [
        ///						&quot;string&quot;,
        ///						&quot;null&quot;
        ///					]
        ///				},
        ///				&quot;scenario&quot;: {
        ///					&quot;required&quot;: false,
        ///					&quot;type&quot;: [
        ///						&quot;string&quot;,
        ///						&quot;null&quot;
        ///					]
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tavern_charactercard_v2_schema {
            get {
                return ResourceManager.GetString("tavern_charactercard_v2_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;name&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: &quot;string&quot;
        ///    },
        ///    &quot;description&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: [
        ///        &quot;string&quot;,
        ///        &quot;null&quot;
        ///      ]
        ///    },
        ///    &quot;scan_depth&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: &quot;integer&quot;
        ///    },
        ///    &quot;token_budget&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: &quot;integer&quot;
        ///    },
        ///    &quot;recursive_scanning&quot;: {
        ///      &quot;required&quot;: false,
        ///      &quot;type&quot;: &quot;boolean&quot;
        ///    },
        ///    &quot;entries&quot;: {
        ///      &quot;requ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tavern_worldbook_schema {
            get {
                return ResourceManager.GetString("tavern_worldbook_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This recipe cannot be added..
        /// </summary>
        internal static string tooltip_cant_add {
            get {
                return ResourceManager.GetString("tooltip_cant_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gender of the character.
        ///This setting affects generated text only..
        /// </summary>
        internal static string tooltip_character_gender {
            get {
                return ResourceManager.GetString("tooltip_character_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of this character card.
        ///Commonly, this is the same as the character&apos;s name..
        /// </summary>
        internal static string tooltip_character_name {
            get {
                return ResourceManager.GetString("tooltip_character_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the pronouns to use for this character.
        ///(This setting affects generated text only.).
        /// </summary>
        internal static string tooltip_character_pronouns {
            get {
                return ResourceManager.GetString("tooltip_character_pronouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the list of recently used files..
        /// </summary>
        internal static string tooltip_clear_mru {
            get {
                return ResourceManager.GetString("tooltip_clear_mru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new recipe and add it to your recipe book.
        /// </summary>
        internal static string tooltip_create_recipe {
            get {
                return ResourceManager.GetString("tooltip_create_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new snippet.
        /// </summary>
        internal static string tooltip_create_snippet {
            get {
                return ResourceManager.GetString("tooltip_create_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the creator of this card..
        /// </summary>
        internal static string tooltip_creator {
            get {
                return ResourceManager.GetString("tooltip_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comment from the creator..
        /// </summary>
        internal static string tooltip_creator_notes {
            get {
                return ResourceManager.GetString("tooltip_creator_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informs recipes and affects level of detail in generated text.
        ///Higher detail increases token count..
        /// </summary>
        internal static string tooltip_detail_level {
            get {
                return ResourceManager.GetString("tooltip_detail_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge all lorebooks into one.
        /// </summary>
        internal static string tooltip_merge_lorebooks {
            get {
                return ResourceManager.GetString("tooltip_merge_lorebooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        internal static string tooltip_move_down {
            get {
                return ResourceManager.GetString("tooltip_move_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        internal static string tooltip_move_up {
            get {
                return ResourceManager.GetString("tooltip_move_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Hold Shift to not include any complementary recipes.).
        /// </summary>
        internal static string tooltip_no_includes {
            get {
                return ResourceManager.GetString("tooltip_no_includes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click or drag a file to change portrait image..
        /// </summary>
        internal static string tooltip_no_portrait_image {
            get {
                return ResourceManager.GetString("tooltip_no_portrait_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open text editor.
        /// </summary>
        internal static string tooltip_open_write {
            get {
                return ResourceManager.GetString("tooltip_open_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable &quot;Not Safe For Work&quot; content.
        /// </summary>
        internal static string tooltip_option_nsfw {
            get {
                return ResourceManager.GetString("tooltip_option_nsfw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically convert name placeholders.
        /// </summary>
        internal static string tooltip_option_use_placeholders {
            get {
                return ResourceManager.GetString("tooltip_option_use_placeholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click to change portrait..
        /// </summary>
        internal static string tooltip_portrait_image {
            get {
                return ResourceManager.GetString("tooltip_portrait_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bake this recipe to editable text..
        /// </summary>
        internal static string tooltip_recipe_bake {
            get {
                return ResourceManager.GetString("tooltip_recipe_bake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new recipe from this recipe..
        /// </summary>
        internal static string tooltip_recipe_create_recipe {
            get {
                return ResourceManager.GetString("tooltip_recipe_create_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a snippet from this recipe..
        /// </summary>
        internal static string tooltip_recipe_create_snippet {
            get {
                return ResourceManager.GetString("tooltip_recipe_create_snippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles whether the text is formatted..
        /// </summary>
        internal static string tooltip_recipe_formatting {
            get {
                return ResourceManager.GetString("tooltip_recipe_formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a local copy of this recipe..
        /// </summary>
        internal static string tooltip_recipe_load_local {
            get {
                return ResourceManager.GetString("tooltip_recipe_load_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a local copy of this recipe..
        /// </summary>
        internal static string tooltip_recipe_save_local {
            get {
                return ResourceManager.GetString("tooltip_recipe_save_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload all recipes from disk.
        /// </summary>
        internal static string tooltip_reload_recipes {
            get {
                return ResourceManager.GetString("tooltip_reload_recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove entry.
        /// </summary>
        internal static string tooltip_remove_lore {
            get {
                return ResourceManager.GetString("tooltip_remove_lore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save an incremental copy of this card.
        /// </summary>
        internal static string tooltip_save_incremental {
            get {
                return ResourceManager.GetString("tooltip_save_incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spoken name of the character (what they they go by).
        ///Same as card name if omitted..
        /// </summary>
        internal static string tooltip_spoken_name {
            get {
                return ResourceManager.GetString("tooltip_spoken_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of descriptive tags for this card..
        /// </summary>
        internal static string tooltip_tags {
            get {
                return ResourceManager.GetString("tooltip_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusts the format of the character&apos;s responses.
        ///(This setting only applies to greetings and example chat.).
        /// </summary>
        internal static string tooltip_text_style {
            get {
                return ResourceManager.GetString("tooltip_text_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total context size that the character occupies (measured in Llama2 tokens)..
        /// </summary>
        internal static string tooltip_tokens {
            get {
                return ResourceManager.GetString("tooltip_tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum context size that the character can occupy (measured in Llama2 tokens)..
        /// </summary>
        internal static string tooltip_tokens_permanent {
            get {
                return ResourceManager.GetString("tooltip_tokens_permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gender or desired point of view of the user.
        ///This setting affects generated text only..
        /// </summary>
        internal static string tooltip_user_gender {
            get {
                return ResourceManager.GetString("tooltip_user_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name to use in place of {user}.
        ///(Is not stored in the character card.).
        /// </summary>
        internal static string tooltip_user_name {
            get {
                return ResourceManager.GetString("tooltip_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A version number or version name for this card..
        /// </summary>
        internal static string tooltip_version {
            get {
                return ResourceManager.GetString("tooltip_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ginger id=&quot;__user-persona&quot;&gt;
        ///	&lt;Name&gt;User persona&lt;/Name&gt;
        ///	&lt;Color&gt;#ddf5ef&lt;/Color&gt;
        ///	&lt;Order&gt;2&lt;/Order&gt;
        ///	&lt;Multiple&gt;True&lt;/Multiple&gt;
        ///	&lt;Requires&gt;not __actor&lt;/Requires&gt;
        ///	&lt;Flags&gt;user-persona, __user, __component, __formatting, __internal&lt;/Flags&gt;
        ///	
        ///	&lt;Text id=&quot;user-persona&quot; style=&quot;component&quot;&gt;
        ///		&lt;Label&gt;Description&lt;/Label&gt;
        ///	&lt;/Text&gt;
        ///	
        ///	&lt;User&gt;{user-persona:local}&lt;/User&gt;
        ///&lt;/Ginger&gt;.
        /// </summary>
        internal static string user_recipe {
            get {
                return ResourceManager.GetString("user_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap write {
            get {
                object obj = ResourceManager.GetObject("write", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
